In [2]:
import pandas as pd
import numpy as np

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames

# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2 Create a 3x4 NumPy array with random integers between 1 and 100
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

# 1.3 Convert NumPy array into DataFrame
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print(s1_1)
print(np_array1_2)
print(df1_3)

0    10
1    20
2    30
3    40
4    50
dtype: int64
[[28  1 33 54]
 [ 2 23 80 40]
 [19 86 17 96]]
    A   B   C   D
0  28   1  33  54
1   2  23  80  40
2  19  86  17  96


In [3]:
# Task 2: Synthetic Data Generation for Practice

# Create the Date column
dates = pd.date_range(start='2023-01-01', end='2023-04-09', periods=100)

# Create the DataFrame
df_sales = pd.DataFrame({
    'Date': dates,
    'Region': np.random.choice(['East', 'West', 'North', 'South'], 100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 100),
    'Sales': np.random.randint(100, 1001, 100),
    'Quantity': np.random.randint(1, 11, 100)
})

# Introduce 5 random NaN values in Sales
sales_nan_indices = np.random.choice(df_sales.index, 5, replace=False)
df_sales.loc[sales_nan_indices, 'Sales'] = np.nan

# Introduce 3 random NaN values in Quantity
quantity_nan_indices = np.random.choice(df_sales.index, 3, replace=False)
df_sales.loc[quantity_nan_indices, 'Quantity'] = np.nan

print(df_sales)

                            Date Region   Product  Sales  Quantity
0  2023-01-01 00:00:00.000000000   East   Monitor  158.0       4.0
1  2023-01-01 23:45:27.272727272  South    Laptop  234.0       2.0
2  2023-01-02 23:30:54.545454545  North     Mouse  362.0       7.0
3  2023-01-03 23:16:21.818181818  North     Mouse  560.0       5.0
4  2023-01-04 23:01:49.090909090   East    Laptop  551.0       9.0
..                           ...    ...       ...    ...       ...
95 2023-04-05 00:58:10.909090910   West     Mouse  324.0       5.0
96 2023-04-06 00:43:38.181818182  North     Mouse  501.0       NaN
97 2023-04-07 00:29:05.454545455   West  Keyboard  111.0       1.0
98 2023-04-08 00:14:32.727272728  North    Laptop  487.0       8.0
99 2023-04-09 00:00:00.000000000  South     Mouse  978.0       8.0

[100 rows x 5 columns]


In [4]:
# Task 3: Indexing and Slicing in DataFrames

# 3.1 Select Region and Sales columns
df3_1 = df_sales[['Region', 'Sales']]

# 3.2 Select rows where Product is Laptop
df3_2 = df_sales[df_sales['Product'] == 'Laptop']

# 3.3 Select rows where Region is East AND Sales > 500
df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]

# 3.4 Select Sales value for the first entry where Product is Monitor
monitor_index = df_sales.index[df_sales['Product'] == 'Monitor'][0]

val3_4 = df_sales.loc[monitor_index, 'Sales']

# Using iloc as well
position = df_sales.index.get_loc(monitor_index)
val3_4 = df_sales.iloc[position]['Sales']

print(df3_1)
print(df3_2)
print(df3_3)
print("First Monitor Sales:", val3_4)

   Region  Sales
0    East  158.0
1   South  234.0
2   North  362.0
3   North  560.0
4    East  551.0
..    ...    ...
95   West  324.0
96  North  501.0
97   West  111.0
98  North  487.0
99  South  978.0

[100 rows x 2 columns]
                            Date Region Product  Sales  Quantity
1  2023-01-01 23:45:27.272727272  South  Laptop  234.0       2.0
4  2023-01-04 23:01:49.090909090   East  Laptop  551.0       9.0
7  2023-01-07 22:18:10.909090909  South  Laptop  666.0       9.0
12 2023-01-12 21:05:27.272727272   West  Laptop  279.0       8.0
20 2023-01-20 19:09:05.454545454   West  Laptop  803.0      10.0
22 2023-01-22 18:40:00.000000000  South  Laptop  422.0       2.0
25 2023-01-25 17:56:21.818181818  South  Laptop  233.0       5.0
26 2023-01-26 17:41:49.090909091  South  Laptop  595.0       3.0
32 2023-02-01 16:14:32.727272727   East  Laptop  205.0       5.0
35 2023-02-04 15:30:54.545454545  South  Laptop  723.0       5.0
39 2023-02-08 14:32:43.636363636  North  Laptop  982.0   

In [5]:
# Task 4: Data Cleaning (Handling Missing Values)

# 4.1 Check missing values in each column
missing_counts4_1 = df_sales.isna().sum()

# 4.2 Fill missing Sales values with mean Sales
df4_2_filled = df_sales.copy()

df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(
    df4_2_filled['Sales'].mean()
)

# 4.3 Drop rows having any missing values
df4_3_dropped = df_sales.dropna()

print("Missing values:")
print(missing_counts4_1)

print("\nDataFrame after filling Sales:")
print(df4_2_filled)

print("\nDataFrame after dropping missing rows:")
print(df4_3_dropped)

Missing values:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

DataFrame after filling Sales:
                            Date Region   Product  Sales  Quantity
0  2023-01-01 00:00:00.000000000   East   Monitor  158.0       4.0
1  2023-01-01 23:45:27.272727272  South    Laptop  234.0       2.0
2  2023-01-02 23:30:54.545454545  North     Mouse  362.0       7.0
3  2023-01-03 23:16:21.818181818  North     Mouse  560.0       5.0
4  2023-01-04 23:01:49.090909090   East    Laptop  551.0       9.0
..                           ...    ...       ...    ...       ...
95 2023-04-05 00:58:10.909090910   West     Mouse  324.0       5.0
96 2023-04-06 00:43:38.181818182  North     Mouse  501.0       NaN
97 2023-04-07 00:29:05.454545455   West  Keyboard  111.0       1.0
98 2023-04-08 00:14:32.727272728  North    Laptop  487.0       8.0
99 2023-04-09 00:00:00.000000000  South     Mouse  978.0       8.0

[100 rows x 5 columns]

DataFrame after dropping missing rows:
 

In [6]:
# Task 5: Data Manipulation (Columns, Sorting, Grouping)

# 5.1 Create Total_Revenue column
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

# 5.2 Sort by Date ascending, then Sales descending
df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)

# 5.3 Group by Region and calculate sum of Sales and Quantity
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

# 5.4 Group by Product and calculate average Sales
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("Sorted DataFrame:")
print(df5_2_sorted)

print("\nGrouped by Region:")
print(df5_3_grouped_region)

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)

Sorted DataFrame:
                            Date Region   Product  Sales  Quantity  \
0  2023-01-01 00:00:00.000000000   East   Monitor  158.0       4.0   
1  2023-01-01 23:45:27.272727272  South    Laptop  234.0       2.0   
2  2023-01-02 23:30:54.545454545  North     Mouse  362.0       7.0   
3  2023-01-03 23:16:21.818181818  North     Mouse  560.0       5.0   
4  2023-01-04 23:01:49.090909090   East    Laptop  551.0       9.0   
..                           ...    ...       ...    ...       ...   
95 2023-04-05 00:58:10.909090910   West     Mouse  324.0       5.0   
96 2023-04-06 00:43:38.181818182  North     Mouse  501.0       NaN   
97 2023-04-07 00:29:05.454545455   West  Keyboard  111.0       1.0   
98 2023-04-08 00:14:32.727272728  North    Laptop  487.0       8.0   
99 2023-04-09 00:00:00.000000000  South     Mouse  978.0       8.0   

    Total_Revenue  
0           632.0  
1           468.0  
2          2534.0  
3          2800.0  
4          4959.0  
..            ...  
9